<a href="https://colab.research.google.com/github/andreacecchini/ml-dojo/blob/main/playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Playground

In [1]:
import numpy as np
import torch

In [15]:
x = np.array([1, 2, 3, 4]).reshape(4, 1)
x.shape, x

((4, 1),
 array([[1],
        [2],
        [3],
        [4]]))

In [16]:
y = np.array([1, 2, 3, 4]).reshape(1, 4)
y.shape, y

((1, 4), array([[1, 2, 3, 4]]))

In [19]:
x @ y

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [20]:
y @ x

array([[30]])

In [27]:
(x @ y) @ x

array([[ 30],
       [ 60],
       [ 90],
       [120]])

In [28]:
y @ (x @ y)

array([[ 30,  60,  90, 120]])

In [29]:
y @ (x @ y) @ x

array([[900]])